### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by ShoufaChen** [ZhaoyangLyu/Early_Stopped_DDPM#1]
Dear Zhaoyang,

Thanks for your awesome work.

Could you please provide the training script? Did you use the fp16?

**Comment by ZhaoyangLyu** [comment]
Thanks for your question!  We do not train DDPMs on ImageNet or LSUN datasets by ourselves. We use pretrained checkpoints from the repo https://github.com/openai/guided-diffusion as described in ReadMe.

**Comment by ShoufaChen** [comment]
Thanks for reply.
